version: '2'
services:
  web:
    container_name: middleware
    image: middleware
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - /code
    command: /bin/bash   

  data:
    restart: 'no'
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: 'true'

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"